### ISSUE TITLE
PR, Commit message templete 추가

### ISSUE THREAD

**Issue by KumaHoon** [KumaHoon/OSDA-bot#11]
좋은 커밋 메세지를 남기기 위해 양식을 통일해야한다는 생각이 들어서 템플릿 논의입니다.

**Comment by aelrot12** [comment]
일단 제목 같은 경우는 기존 `Add ~~.py` 형식을 유지하는 것이 좋을 것 같습니다.
문제가 있는 부분은 세부 커밋 메시지 형태가 자유 형식으로 되어있어 커밋을 한 번에 구분하기 힘들다는 점인 것 같습니다.
`(개발자 or 변경자)/ 날짜 / 변경사항 `
형식으로 통일하면 이러한 단점들을 없앨 수 있을 것입니다.

**Comment by KumaHoon** [comment]
그리고 이슈 번호도 추가하면 좋을 것 같습니다!

https://git-scm.com/book/ko/v2/Git%EB%A7%9E%EC%B6%A4-Git-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0를 참고해서 만들었습니다!

1. 가이드에 따라 ~/.gitmessage.txt 파일을 만든다.
touch ~/.gitmessage.txt
2. 텍스트 에디터로 들어간다(예 : vim)
vim ~/.gitmessage.txt
3. 양식을 copy & paste한다. 그리고 :wq 를 사용해 종료한다.
4. commit.template 에 이 파일을 설정해줍니다.
git config --global commit.template ~/.gitmessage.txt
(git commit -m으로 하시면 생략됩니다)


-----------------------<양식>--------------------------------------
# <타입>: <제목>

##### 제목은 최대 50 글자까지만 입력 ############## -> |


# 본문은 위에 작성
######## 본문은 한 줄에 최대 72 글자까지만 입력 ########################### -> |

# 꼬릿말은 아래에 작성: ex) #이슈 번호, 개발자, 날짜(커밋 내용과 관계 없는 것들)

# --- COMMIT END ---
# <타입> 리스트
#   feat    : 기능 (새로운 기능)
#   fix     : 버그 (버그 수정)
#   style   : 스타일 (코드 형식, 세미콜론 추가: 비즈니스 로직에 변경 없음)
#   docs    : 문서 (문서 추가, 수정, 삭제)
#   test    : 테스트 (테스트 코드 추가, 수정, 삭제: 비즈니스 로직에 변경 없음)

# ------------------
#     제목 첫 글자를 대문자로
#     제목은 명령문으로
#     제목 끝에 마침표(.) 금지
#     제목과 본문을 한 줄 띄워 분리하기
#     본문은 "어떻게" 보다 "무엇을", "왜"를 설명한다.
#     본문에 여러줄의 메시지를 작성할 땐 "-"로 구분
# ------------------

**Comment by ItsNotDead** [comment]
It will be better if you guys use English also cause everyone on git doesn't know Korean like me.
I hope you understand this.
