### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ItsNotDead** [KumaHoon/OSDA-bot#18]
Hey, Hope you guys are safe and enjoying your work. I was watching your code and I realize you guys are not using any kind of prefix Idk what is in your mind but if you don't know you can use the prefix. [Sorry if you guys already know this for have a great idea in mind ] :D

**Comment by KumaHoon** [comment]
Hi, Thank you for your advice! I haven't recognize the prefix that I can use. We'll use it next commit If I can. Thank you for your information!! 👍

**Comment by ItsNotDead** [comment]
hey, I know this is not the right place but can you guys tell me how you guys are making each file for each feature basically how you will run those features?
